FROM python:3.7-alpine

COPY hello_there.py /

# pass an array to CMD, first element is the executable, in this case "python"  
# and the other element is the arguement to execute.
CMD ["python", "hello_there.py" ]